// <auto-generated />
namespace issFinacial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m313 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m313));
        
        string IMigrationMetadata.Id
        {
            get { return "202112100304057_m313"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
